version: "3.9"
services:
  api:
    image: "d0ckmg/free-gpt4-web-api:latest"
    #build: .
    user: www-data
    ports:
      - "5500:5500"
    command: --password testi --enable-gui --remove-sources --provider You --cookie-file /app/src/data/cookies.json
    #command: --remove-sources
